name: Update Docker Image

on:
  schedule:
    - cron: "30 7 * * 6" # Runs every Saturday at 7:30 AM
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push new image
        run: |
          docker build -f ./Containerfile -t atb00ker/jellyfin:latest ./
          docker push atb00ker/jellyfin:latest
